name: wayo
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.5.1
  custom_marker: ^1.0.0
  dio: ^4.0.6
  equatable: ^2.0.5
  feather_icons: ^1.2.0
  firebase_app_check: ^0.0.9+1
  firebase_core: ^1.23.0
  firebase_messaging: ^13.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_inappwebview: ^5.7.1
  get_it: ^7.2.0
  go_router: ^4.5.0
  google_maps_flutter: ^2.2.0
  grouped_list: ^5.1.2
  json_annotation: ^4.7.0
  keyboard_dismisser: ^3.0.0
  location: ^4.4.0
  shared_preferences: ^2.0.15
  sized_context: ^1.0.0+1
  text_scroll: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.4.0
  build_runner: ^2.2.1

uses-material-icons: true

flutter:
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/sounds/
    - assets/web/
    - assets/web/models/
    - assets/web/index.html

  fonts:
    - family: AvantGarde
      fonts:
        - asset: assets/fonts/AvantGarde_Book.ttf
        - asset: assets/fonts/AvantGarde_Book_Oblique.ttf
          style: italic
        - asset: assets/fonts/AvantGarde_Demi.ttf
          weight: 700
        - asset: assets/fonts/AvantGarde_Demi_Oblique.ttf
          weight: 700
          style: italic
