name: wayo
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  dio: ^5.1.1
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_inappwebview: ^5.7.2+3
  flutter_map: ^4.0.0
  flutter_svg: ^2.0.5
  get_it: ^7.2.0
  go_router: ^10.1.2
  grouped_list: ^5.1.2
  is_first_run: ^1.0.0
  json_annotation: ^4.8.0
  keyboard_dismisser: ^3.0.0
  latlong2: ^0.8.1
  location: ^5.0.3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  sized_context: ^1.0.0+1
  sliver_tools: ^0.2.10
  text_scroll: ^0.2.0
  url_launcher: ^6.1.10
  video_player: ^2.6.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.1.11
  analyzer: ^5.2.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/splash/
    - assets/images/splash/row1/
    - assets/images/splash/row2/
    - assets/images/splash/row3/
    - assets/images/splash/row4/
    - assets/images/onboarding/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
